id: I0404BC8A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T18:25:18+00:00'
last_modified: '2022-06-08T07:12:58.120425+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD133163
  title: ཞེ་ཆེ་རྒྱལ་ཚབ་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ་གྱི་གསུང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BC64:
      image_group_id: I4PD2441
      title: ''
      total_pages: 530
      order: 1
      base_file: BC64.txt
    '6717':
      image_group_id: I4PD2442
      title: ''
      total_pages: 490
      order: 2
      base_file: 6717.txt
    EABB:
      image_group_id: I4PD2443
      title: ''
      total_pages: 448
      order: 3
      base_file: EABB.txt
    EED5:
      image_group_id: I4PD2444
      title: ''
      total_pages: 528
      order: 4
      base_file: EED5.txt
    C671:
      image_group_id: I4PD2445
      title: ''
      total_pages: 486
      order: 5
      base_file: C671.txt
    EC8A:
      image_group_id: I4PD2446
      title: ''
      total_pages: 436
      order: 6
      base_file: EC8A.txt
    D21B:
      image_group_id: I4PD2447
      title: ''
      total_pages: 496
      order: 7
      base_file: D21B.txt
    C69F:
      image_group_id: I4PD2448
      title: ''
      total_pages: 696
      order: 8
      base_file: C69F.txt
    79BD:
      image_group_id: I4PD2449
      title: ''
      total_pages: 658
      order: 9
      base_file: 79BD.txt
    0E99:
      image_group_id: I4PD2450
      title: ''
      total_pages: 572
      order: 10
      base_file: 0E99.txt
    6E33:
      image_group_id: I4PD2451
      title: ''
      total_pages: 604
      order: 11
      base_file: 6E33.txt
    '8093':
      image_group_id: I4PD2452
      title: ''
      total_pages: 680
      order: 12
      base_file: 8093.txt
    6B46:
      image_group_id: I4PD2453
      title: ''
      total_pages: 580
      order: 13
      base_file: 6B46.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
