id: I0404BC8A
legacy_id: P006839
ocr_import_info:
  bdrc_scan_id: W1PD133163
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T18:18:43'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T02:17:03.420407+00:00'
last_modified: 2022-09-01 10:23:29.723056
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD133163
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1PD133163
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞེ་ཆེ་རྒྱལ་ཚབ་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ་གྱི་གསུང་འབུམ།
  author: ཞེ་ཆེན་རྒྱལ་ཚབ ༠༤་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.8156618196616496
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4PD2447:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2447
      total_pages: 496
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4PD2447.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8008185054403846
    legacy_id: v007
  I4PD2452:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2452
      total_pages: 680
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I4PD2452.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8123451175299023
    legacy_id: v012
  I4PD2444:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2444
      total_pages: 528
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4PD2444.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8262412001144397
    legacy_id: v004
  I4PD2442:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2442
      total_pages: 490
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD2442.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8484117098758636
    legacy_id: v002
  I4PD2451:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2451
      total_pages: 604
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I4PD2451.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8026377166099468
    legacy_id: v011
  I4PD2446:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2446
      total_pages: 436
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4PD2446.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8279974437156326
    legacy_id: v006
  I4PD2449:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2449
      total_pages: 658
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I4PD2449.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8193149538661872
    legacy_id: v009
  I4PD2448:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2448
      total_pages: 696
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4PD2448.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.7741390106483745
    legacy_id: v008
  I4PD2453:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2453
      total_pages: 580
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I4PD2453.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8176318184552305
    legacy_id: v013
  I4PD2441:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2441
      total_pages: 530
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD2441.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8559900790923103
    legacy_id: v001
  I4PD2445:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2445
      total_pages: 486
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4PD2445.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8173859131805302
    legacy_id: v005
  I4PD2450:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2450
      total_pages: 572
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I4PD2450.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8050141237459074
    legacy_id: v010
  I4PD2443:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2443
      total_pages: 448
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4PD2443.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8021489725979721
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
