id: P006839
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD133163
  title: ཞེ་ཆེ་རྒྱལ་ཚབ་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ་གྱི་གསུང་འབུམ།
  author: ''
  volumes:
    7f35dc317e8041a682a8fe65682935f5:
      image_group_id: I4PD2441
      title: ''
      volume_number: 1
      total_pages: 530
      base_file: v001.txt
    bd3a1e79530b4a54b4f446bddcd219c1:
      image_group_id: I4PD2442
      title: ''
      volume_number: 2
      total_pages: 490
      base_file: v002.txt
    725251067ea1469eaa3e9d537c4d8a80:
      image_group_id: I4PD2443
      title: ''
      volume_number: 3
      total_pages: 448
      base_file: v003.txt
    c13d5deda67c4bd9a858890b93316a9b:
      image_group_id: I4PD2444
      title: ''
      volume_number: 4
      total_pages: 528
      base_file: v004.txt
    97ab6f5a90bd431498d683a70d3477ed:
      image_group_id: I4PD2445
      title: ''
      volume_number: 5
      total_pages: 486
      base_file: v005.txt
    8178be04b29c4822b4a2d65988b48d84:
      image_group_id: I4PD2446
      title: ''
      volume_number: 6
      total_pages: 436
      base_file: v006.txt
    72bdfcb4bf344e088b3be99cc412f4e5:
      image_group_id: I4PD2447
      title: ''
      volume_number: 7
      total_pages: 496
      base_file: v007.txt
    1a38d2f0ed31420dbe1df47f80e2d039:
      image_group_id: I4PD2448
      title: ''
      volume_number: 8
      total_pages: 696
      base_file: v008.txt
    1a95d0aa28cd44589756f4345d9e86a7:
      image_group_id: I4PD2449
      title: ''
      volume_number: 9
      total_pages: 658
      base_file: v009.txt
    c802852d175841e9aea9dd23df75a847:
      image_group_id: I4PD2450
      title: ''
      volume_number: 10
      total_pages: 572
      base_file: v010.txt
    790a8a36f3e643b4908b7b20c8b3a966:
      image_group_id: I4PD2451
      title: ''
      volume_number: 11
      total_pages: 604
      base_file: v011.txt
    98b30b56176e4b459a7a8948b0a210d1:
      image_group_id: I4PD2452
      title: ''
      volume_number: 12
      total_pages: 680
      base_file: v012.txt
    fe120bdf019a4bf2bd335618f74777f1:
      image_group_id: I4PD2453
      title: ''
      volume_number: 13
      total_pages: 580
      base_file: v013.txt
